import wp1 from "../assets/images/wp1.jpg";
import wp2 from "../assets/images/wp2.jpg";
import wp3 from "../assets/images/wp3.jpg";
import wp4 from "../assets/images/wp4.jpg";
import wp5 from "../assets/images/wp5.jpg";
import wp6 from "../assets/images/wp6.jpg";
import wp7 from "../assets/images/wp7.jpg";
import wp8 from "../assets/images/wp8.jpg";
import wp9 from "../assets/images/wp9.jpg";
import wp10 from "../assets/images/wp10.jpg";
import wp11 from "../assets/images/wp11.jpg";
import wp12 from "../assets/images/wp12.jpg";
export { wp1, wp2, wp3, wp4, wp5, wp6, wp7, wp8, wp9, wp10, wp11, wp12 };
